<a href="https://colab.research.google.com/github/datacuriosity/Data_Analytic/blob/main/anguyen_1612.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
np.array(['toi',1])

array(['toi', '1'], dtype='<U3')

In [5]:
np.array([1, 2, 3, 4], dtype='float')

array([1., 2., 3., 4.])

In [9]:
arr = np.arange(1, 10, 1).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1, 10, 1).reshape(3, 3).size

9

In [10]:
# np.sum(arr)
arr.sum()

45

In [11]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [18]:
arr.sum(axis=0)

array([12, 15, 18])

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Element wise
- chiều thứ 1 là dòng (row), chiều thứ 2 là cột (column)
- dấu : là lấy hết cột/dòng (:x means x là to x, x là exclusive)

In [17]:
arr + np.array([1, 1, 1])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [21]:
arr * np.array([2, 2, 2])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Dot product a vs b (ứng dụng kỹ thuật giảm chiều dữ liệu)
- Number of columns in a = number of rows in b
$$ A_{m, n} * B_{n, k} = C_{m, k} 
$$

In [26]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr[0, 1:3]

array([2, 3])

![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [32]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[1:,:] # arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr[[0, 2],1:3]

array([[ 2,  3],
       [10, 11]])

### Masking

In [37]:
arr < 7

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [38]:
arr[arr<7]

array([1, 2, 3, 4, 5, 6])

In [40]:
np.where(arr < 7, 1, 0)

array([[1, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 0, 0, 0]])

**Statistic**

In [41]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
arr.sum()

78

In [43]:
arr.sum(axis=0)

array([15, 18, 21, 24])

In [44]:
arr.sum(axis=1)

array([10, 26, 42])

In [46]:
arr_1 = np.arange(1, 13).reshape(2, 2, 3)
arr_1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr_1.sum(axis=2)

array([[ 6, 15],
       [24, 33]])

In [48]:
arr_1.sum(axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [49]:
arr_1.sum(axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [50]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr.max()

12

In [52]:
arr.min()

1

In [53]:
arr.mean() #mean là giá trị trung bình

6.5

Standard normal distribution / One standard deviation = độ lệch chuẩn trong phân phối chuẩn (phân phối chuẩn có hình chuông, trục đối xứng 
(x = điểm chuẩn của giữ liệu, y = số lần xuất hiện, z (độ lệch chuẩn = mức độ phân tán của dữ liệu ~ lượng thông tin gain được (càng phân tán càng nhiều) ==> giá trị mean (trung bình) = giá trị median (giá trị trung vị) = giá trị mode (giá trị có tần xuất xuất hiện nhiều nhất)

Numpy ko có mode -> dùng scipy

In [57]:
arr.std() #standard deviation = độ lệch chuẩn

3.452052529534663

In [55]:
np.median(arr)

6.5

**Random**