In [ ]:
!pip install numpy

In [5]:
import numpy as np

### Create numpy array

- List có thể chứa nhiều kiểu dữ liệu khác nhau
- Array chỉ chứa 1 kiểu dữ liệu 

In [6]:
arr_1D = np.array([1, 2, 3, 4])
arr_1D

array([1, 2, 3, 4])

In [7]:
li = ['toi', 1]
li

['toi', 1]

In [8]:
np.array(['toi', 1])

array(['toi', '1'], dtype='<U3')

In [9]:
np.array([1, 2, 3, 4], dtype='float')

array([1., 2., 3., 4.])

In [12]:
arr_2D = np.array([[1, 2, 3], [1, 3, 4], [4, 5, 6]])

In [13]:
arr_2D

array([[1, 2, 3],
       [1, 3, 4],
       [4, 5, 6]])

In [14]:
arr_2D.shape

(3, 3)

In [18]:
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [19]:
# (3, 3, 2)

arr_3D = np.array([[[1, 2], [3, 4], [5, 6]],
                   [[7, 8], [9, 10], [11, 12]],
                   [[13, 14], [15, 16], [17, 18]]])
arr_3D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [20]:
arr_3D.shape

(3, 3, 2)

In [24]:
np.arange(1, 10, 1).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.arange(1, 10, 1).reshape(3, 3).size

9

In [29]:
arr = np.arange(1, 10, 1).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# np.sum(arr)
arr.sum()

45

In [34]:
arr.sum(axis=0)

array([12, 15, 18])

In [35]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Broadcasting
![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Element wise**

In [40]:
arr + np.array([1, 1, 1])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [41]:
arr * np.array([1, 1, 1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Dot product**

$
A_{m, n} x B_{n, k} = C_{m, k}
$

- Number of columns in a = number of rows in b

In [44]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(1, 10).reshape(3, 3)

In [46]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [47]:
np.dot(a, b)

array([[30, 36, 42],
       [66, 81, 96]])

## Slicing

In [49]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr[0, 1:3]

array([2, 3])

In [52]:
arr[1:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [58]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
arr[[0, 2] , 1:3]

array([[ 2,  3],
       [10, 11]])

**Masking**

In [68]:
arr[arr < 7]

array([1, 2, 3, 4, 5, 6])

In [70]:
np.where(arr < 7, 1, 0)

array([[1, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 0, 0, 0]])

**Statistic**

In [77]:
arr_1 = np.arange(1, 13).reshape(2, 2, 3)

In [78]:
arr_1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr_1.sum(axis=2)

array([[ 6, 15],
       [24, 33]])

In [80]:
arr_1.sum(axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [81]:
arr_1.sum(axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [72]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
arr.sum()

78

In [73]:
arr.sum(axis=0)

array([15, 18, 21, 24])

In [74]:
arr.sum(axis=1)

array([10, 26, 42])

In [75]:
arr.max()

12

In [76]:
arr.max(axis=0)

array([ 9, 10, 11, 12])

In [82]:
arr.min()

1

In [83]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
arr.mean()

6.5

In [85]:
arr.std()

3.452052529534663

In [87]:
np.median(arr)

6.5

### Random 